### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by baroni777** [TBMoonwalker/3cqsbot#9]
Traceback (most recent call last):
  File "C:\Users\solad\3cqsbot-1.0.1-alpha\3cqsbot.py", line 12, in <module>
    from singlebot import SingleBot
  File "C:\Users\solad\3cqsbot-1.0.1-alpha\singlebot.py", line 3, in <module>
    from signals import Signals
  File "C:\Users\solad\3cqsbot-1.0.1-alpha\signals.py", line 7, in <module>
    from pycoingecko import CoinGeckoAPI

**Comment by TBMoonwalker** [comment]
@baroni777 can you please add the messages before and after too?

**Comment by TBMoonwalker** [comment]
because of no feedback - closing that one.
